spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: Wswpr1230

  redis:
    host: localhost
    port: 6379
    database: 0

  # 这里加一个假的 API Key，只为启动项目！
  ai:
    dashscope:
      api-key: "fake-key-for-startup"

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

server:
  port: 8080

jwt:
  secret: demo-jwt-secret-key-for-spring-security-2026
  expiration-millis: 7200000